# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main','pokeDex']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  test_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache-dependency-path: './pokeDex/package-lock.json'
          cache: 'npm'
          # cache-dependency-path: './pokeDex/package-lock.json'
      - name: Install and run Build dependencies
        # working-directory: pokeDex
        run: |
          npm install
          npm run build
      - name: Run test
        # working-directory: pokeDex
        run: npm test
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          # path: './pokeDex/dist'
          ACTIONS_RUNNER_DEBUG: true
      - name: Deploy to GitHub Pages
        id: deployment
        # path: './pokeDex/dist'
        # cache-dependency-path: './pokeDex/package-lock.json'
        uses: actions/deploy-pages@v1
        
